### ISSUE TITLE
macOs build error

### ISSUE THREAD

**Issue by seanmars** [aelij/RoslynPad#235]
```
CSC : error CS1617: Invalid option '8.0' for /langversion. Use '/langversion:?' to list supported values. [/RoslynPad/src/RoslynPad.Roslyn/RoslynPad.Roslyn.csproj]
CSC : error CS1617: Invalid option '8.0' for /langversion. Use '/langversion:?' to list supported values. [/RoslynPad/src/RoslynPad.Common/RoslynPad.Common.csproj]
```

dotnet version:
```
dotnet --info 
.NET Core SDK (reflecting any global.json):
 Version:   2.2.104
 Commit:    73f036d4ac

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.104/

Host (useful for support):
  Version: 2.2.2
  Commit:  a4fd7b2c84

.NET Core SDKs installed:
  2.2.104 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by aelij** [comment]
See #231. On a Mac, I think .NET Core 3.0 SDK might work.

**Comment by aelij** [comment]
The latest commit adds the `Microsoft.Net.Compilers` package, so you should be able to build with the 2.2 SDK / MSBuild 15.9 now.
